In [1]:
from google.colab import files
uploaded = files.upload()

Saving customer_churn_data.csv to customer_churn_data.csv


In [2]:
import pandas as pd

In [3]:
data = pd.read_csv('customer_churn_data.csv')

In [4]:
data.head()

customerID  gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
0   CUST0000    Male              0      No        Yes      23           No   
1   CUST0001  Female              0     Yes         No      43           No   
2   CUST0002    Male              1      No         No      51          Yes   
3   CUST0003    Male              1      No         No      72          Yes   
4   CUST0004    Male              1      No         No      25          Yes   

      MultipleLines InternetService       OnlineSecurity  ...  \
0  No phone service              No  No internet service  ...   
1  No phone service             DSL                  Yes  ...   
2                No             DSL                   No  ...   
3               Yes             DSL                  Yes  ...   
4               Yes             DSL                   No  ...   

      DeviceProtection          TechSupport          StreamingTV  \
0  No internet service  No internet service  No internet service   
1                  Yes                   No                  Yes   
2                  Yes                  Yes                   No   
3                  Yes                   No                   No   
4                   No                  Yes                   No   

       StreamingMovies        Contract PaperlessBilling     PaymentMethod  \
0  No internet service  Month-to-month              Yes     Bank transfer   
1                   No  Month-to-month               No      Mailed check   
2                   No        One year               No  Electronic check   
3                   No  Month-to-month               No       Credit card   
4                  Yes  Month-to-month               No  Electronic check   

  MonthlyCharges  TotalCharges  Churn  
0          49.85       1146.55     No  
1         100.70       4330.10    Yes  
2          97.33       4963.83    Yes  
3         101.38       7299.36     No  
4          52.22       1305.50    Yes  

[5 rows x 21 columns]

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5880 entries, 0 to 5879
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   customerID        5880 non-null   object 
 1   gender            5880 non-null   object 
 2   SeniorCitizen     5880 non-null   int64  
 3   Partner           5880 non-null   object 
 4   Dependents        5880 non-null   object 
 5   tenure            5880 non-null   int64  
 6   PhoneService      5880 non-null   object 
 7   MultipleLines     5880 non-null   object 
 8   InternetService   5880 non-null   object 
 9   OnlineSecurity    5880 non-null   object 
 10  OnlineBackup      5880 non-null   object 
 11  DeviceProtection  5880 non-null   object 
 12  TechSupport       5880 non-null   object 
 13  StreamingTV       5880 non-null   object 
 14  StreamingMovies   5880 non-null   object 
 15  Contract          5880 non-null   object 
 16  PaperlessBilling  5880 non-null   object 


In [6]:
print(data.isnull().sum())

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64


In [7]:
#import libraries
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [8]:
data = data.dropna()

In [9]:
label_encoders = {}
for column in data.select_dtypes(include=['object']).columns:
    label_encoders[column] = LabelEncoder()
    data[column] = label_encoders[column].fit_transform(data[column])

In [10]:
X = data.drop('Churn', axis=1)
y = data['Churn']

In [11]:
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [12]:
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)


In [13]:
print("Training set shape:", X_train.shape)
print("Testing set shape:", X_test.shape)

Training set shape: (4704, 20)
Testing set shape: (1176, 20)


In [14]:
data.tail()

customerID  gender  SeniorCitizen  Partner  Dependents  tenure  \
5875        5875       1              0        1           1      71   
5876        5876       1              0        0           0      22   
5877        5877       0              0        0           0      68   
5878        5878       0              0        1           1      14   
5879        5879       0              1        1           0      23   

      PhoneService  MultipleLines  InternetService  OnlineSecurity  ...  \
5875             1              0                0               2  ...   
5876             1              2                0               0  ...   
5877             0              1                1               2  ...   
5878             0              1                1               2  ...   
5879             1              0                2               1  ...   

      DeviceProtection  TechSupport  StreamingTV  StreamingMovies  Contract  \
5875                 0            2            0                0         0   
5876                 2            2            0                2         1   
5877                 2            2            2                0         1   
5878                 2            2            2                2         0   
5879                 1            1            1                1         0   

      PaperlessBilling  PaymentMethod  MonthlyCharges  TotalCharges  Churn  
5875                 1              3           74.21       5268.91      0  
5876                 0              3           65.43       1439.46      1  
5877                 1              0           59.78       4065.04      0  
5878                 1              3           91.88       1286.32      0  
5879                 0              3           25.45        585.35      1  

[5 rows x 21 columns]

In [15]:
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [16]:
logreg = LogisticRegression()
rf = RandomForestClassifier()
gb = GradientBoostingClassifier()

In [17]:
#Train Logistic Regression Model
logreg.fit(X_train, y_train)

LogisticRegression()

In [18]:
#Train Random Forest Model
rf.fit(X_train, y_train)

RandomForestClassifier()

In [20]:
#Train Gradient Boosting Model
gb.fit(X_train, y_train)

GradientBoostingClassifier()

In [21]:
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    print("Accuracy:", accuracy_score(y_test, y_pred))
    print("Classification Report:\n", classification_report(y_test, y_pred))
    print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

In [22]:
print("Logistic Regression Evaluation:")
evaluate_model(logreg, X_test, y_test)

Logistic Regression Evaluation:
Accuracy: 0.4906462585034014
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.63      0.55       584
           1       0.49      0.35      0.41       592

    accuracy                           0.49      1176
   macro avg       0.49      0.49      0.48      1176
weighted avg       0.49      0.49      0.48      1176

Confusion Matrix:
 [[369 215]
 [384 208]]


In [23]:
print("Random Forest Evaluation:")
evaluate_model(rf, X_test, y_test)

Random Forest Evaluation:
Accuracy: 0.49404761904761907
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.54      0.52       584
           1       0.50      0.45      0.47       592

    accuracy                           0.49      1176
   macro avg       0.49      0.49      0.49      1176
weighted avg       0.49      0.49      0.49      1176

Confusion Matrix:
 [[316 268]
 [327 265]]


In [24]:
print("Gradient Boosting Evaluation:")
evaluate_model(gb, X_test, y_test)

Gradient Boosting Evaluation:
Accuracy: 0.4991496598639456
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.58      0.53       584
           1       0.50      0.42      0.46       592

    accuracy                           0.50      1176
   macro avg       0.50      0.50      0.50      1176
weighted avg       0.50      0.50      0.50      1176

Confusion Matrix:
 [[338 246]
 [343 249]]


In [26]:

import numpy as np
from imblearn.over_sampling import SMOTE
import xgboost as xgb
from lightgbm import LGBMClassifier

/usr/local/lib/python3.10/dist-packages/dask/dataframe/__init__.py:42: FutureWarning: 
Dask dataframe query planning is disabled because dask-expr is not installed.

You can install it with `pip install dask[dataframe]` or `conda install dask`.
This will raise in a future version.

  warnings.warn(msg, FutureWarning)


In [27]:
param_grid = {
    'n_estimators': [100, 200, 300],
    'max_depth': [10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4]
}

In [29]:

from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score

grid_search = GridSearchCV(estimator=rf, param_grid=param_grid, cv=3, n_jobs=-1, verbose=2)
grid_search.fit(X_train, y_train)

Fitting 3 folds for each of 81 candidates, totalling 243 fits


GridSearchCV(cv=3, estimator=RandomForestClassifier(), n_jobs=-1,
             param_grid={'max_depth': [10, 20, 30],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [100, 200, 300]},
             verbose=2)

In [30]:
best_rf = grid_search.best_estimator_

In [31]:
print("Best Random Forest Evaluation:")
evaluate_model(best_rf, X_test, y_test)

Best Random Forest Evaluation:
Accuracy: 0.4957482993197279
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.57      0.53       584
           1       0.50      0.42      0.46       592

    accuracy                           0.50      1176
   macro avg       0.50      0.50      0.49      1176
weighted avg       0.50      0.50      0.49      1176

Confusion Matrix:
 [[333 251]
 [342 250]]


In [32]:
xgb_model = xgb.XGBClassifier()
xgb_model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [33]:
lgbm_model = LGBMClassifier()
lgbm_model.fit(X_train, y_train)


[LightGBM] [Info] Number of positive: 2306, number of negative: 2398
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000999 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 897
[LightGBM] [Info] Number of data points in the train set: 4704, number of used features: 20
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.490221 -> initscore=-0.039121
[LightGBM] [Info] Start training from score -0.039121


LGBMClassifier()

In [34]:
print("XGBoost Evaluation:")
evaluate_model(xgb_model, X_test, y_test)

XGBoost Evaluation:
Accuracy: 0.4991496598639456
Classification Report:
               precision    recall  f1-score   support

           0       0.50      0.52      0.51       584
           1       0.50      0.48      0.49       592

    accuracy                           0.50      1176
   macro avg       0.50      0.50      0.50      1176
weighted avg       0.50      0.50      0.50      1176

Confusion Matrix:
 [[303 281]
 [308 284]]


In [35]:
print("LightGBM Evaluation:")
evaluate_model(lgbm_model, X_test, y_test)

LightGBM Evaluation:
Accuracy: 0.4965986394557823
Classification Report:
               precision    recall  f1-score   support

           0       0.49      0.53      0.51       584
           1       0.50      0.46      0.48       592

    accuracy                           0.50      1176
   macro avg       0.50      0.50      0.50      1176
weighted avg       0.50      0.50      0.50      1176

Confusion Matrix:
 [[312 272]
 [320 272]]


In [36]:
cv_scores = cross_val_score(logreg, X_train, y_train, cv=5)
print("Cross-validation scores for Logistic Regression:", cv_scores)
print("Mean cross-validation score:", np.mean(cv_scores))

Cross-validation scores for Logistic Regression: [0.52072264 0.49309245 0.49521785 0.49521785 0.49042553]
Mean cross-validation score: 0.4989352657878672
